# Generated by Django 3.2.18 on 2023-07-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0017_auto_20230728_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leket_DB_new',
        ),
    ]
