# Generated by Django 3.2.18 on 2023-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0018_delete_leket_db_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='TMY_station',
            field=models.CharField(max_length=200, null=True, verbose_name='TMY_station'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='aklim_area',
            field=models.CharField(max_length=200, null=True, verbose_name='aklim_area'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='leket_location',
            field=models.CharField(max_length=200, verbose_name='leket_location'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='napa_name',
            field=models.CharField(max_length=200, verbose_name='napa_name'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='station',
            field=models.CharField(max_length=200, null=True, verbose_name='station'),
        ),
    ]
