# Generated by Django 3.2.18 on 2023-07-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0016_auto_20230624_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leket_DB',
        ),
        migrations.DeleteModel(
            name='Users1',
        ),
    ]
