# Generated by Django 3.2.18 on 2023-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0019_auto_20230731_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leket_DB_24_06',
            new_name='leket_DB',
        ),
    ]
